name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker test
        uses: xorblo-doitus/godot-gut-ci@main
        with:
          godot_version: 4.2
          gut_params: -gconfig=res://.gut_editor_config.json